In [19]:
import pandas as pd

In [20]:
data = pd.read_csv('survey-consumer-finances-data.csv')

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207640 entries, 0 to 207639
Data columns (total 4 columns):
CASEID    207640 non-null int64
YEAR      207640 non-null int64
SAVING    207640 non-null float64
MMDA      207640 non-null float64
dtypes: float64(2), int64(2)
memory usage: 6.3 MB

In [22]:
data['TOTAL_SAVINGS'] = data['SAVING'] + data['MMDA']

In [23]:
data_2013 = data[data.YEAR == 2013]

In [24]:
data_2013

        CASEID  YEAR   SAVING     MMDA  TOTAL_SAVINGS
177565  177566  2013      0.0      0.0            0.0
177566  177567  2013      0.0      0.0            0.0
177567  177568  2013      0.0      0.0            0.0
177568  177569  2013      0.0      0.0            0.0
177569  177570  2013      0.0      0.0            0.0
177570  177571  2013   1000.0      0.0         1000.0
177571  177572  2013   1000.0      0.0         1000.0
177572  177573  2013   1000.0      0.0         1000.0
177573  177574  2013   1000.0      0.0         1000.0
177574  177575  2013   1000.0      0.0         1000.0
177575  177576  2013      0.0      0.0            0.0
177576  177577  2013      0.0      0.0            0.0
177577  177578  2013      0.0      0.0            0.0
177578  177579  2013      0.0      0.0            0.0
177579  177580  2013      0.0      0.0            0.0
177580  177581  2013   1200.0  37000.0        38200.0
177581  177582  2013   1200.0  37000.0        38200.0
177582  177583  2013   1200.0  37000.0        38200.0
177583  177584  2013   1200.0  37000.0        38200.0
177584  177585  2013   1200.0  37000.0        38200.0
177585  177586  2013      0.0  30000.0        30000.0
177586  177587  2013      0.0  30000.0        30000.0
177587  177588  2013      0.0  30000.0        30000.0
177588  177589  2013      0.0  30000.0        30000.0
177589  177590  2013      0.0  30000.0        30000.0
177590  177591  2013      0.0      0.0            0.0
177591  177592  2013      0.0      0.0            0.0
177592  177593  2013      0.0      0.0            0.0
177593  177594  2013      0.0      0.0            0.0
177594  177595  2013      0.0      0.0            0.0
...        ...   ...      ...      ...            ...
207610  207611  2013  70000.0      0.0        70000.0
207611  207612  2013  70000.0      0.0        70000.0
207612  207613  2013  70000.0      0.0        70000.0
207613  207614  2013  70000.0      0.0        70000.0
207614  207615  2013  70000.0      0.0        70000.0
207615  207616  2013      0.0  27000.0        27000.0
207616  207617  2013      0.0  32000.0        32000.0
207617  207618  2013      0.0  41000.0        41000.0
207618  207619  2013      0.0  32000.0        32000.0
207619  207620  2013      0.0  44000.0        44000.0
207620  207621  2013      0.0      0.0            0.0
207621  207622  2013      0.0      0.0            0.0
207622  207623  2013      0.0      0.0            0.0
207623  207624  2013      0.0      0.0            0.0
207624  207625  2013      0.0      0.0            0.0
207625  207626  2013   1200.0      0.0         1200.0
207626  207627  2013   1200.0      0.0         1200.0
207627  207628  2013   1300.0      0.0         1300.0
207628  207629  2013   1300.0      0.0         1300.0
207629  207630  2013   1100.0      0.0         1100.0
207630  207631  2013      0.0      0.0            0.0
207631  207632  2013      0.0      0.0            0.0
207632  207633  2013      0.0      0.0            0.0
207633  207634  2013      0.0      0.0            0.0
207634  207635  2013      0.0      0.0            0.0
207635  207636  2013      0.0      0.0            0.0
207636  207637  2013      0.0      0.0            0.0
207637  207638  2013      0.0      0.0            0.0
207638  207639  2013      0.0      0.0            0.0
207639  207640  2013      0.0      0.0            0.0

[30075 rows x 5 columns]

In [25]:
data_2013.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30075 entries, 177565 to 207639
Data columns (total 5 columns):
CASEID           30075 non-null int64
YEAR             30075 non-null int64
SAVING           30075 non-null float64
MMDA             30075 non-null float64
TOTAL_SAVINGS    30075 non-null float64
dtypes: float64(3), int64(2)
memory usage: 1.4 MB

In [26]:
total_savings_data_2013=data_2013[['CASEID','TOTAL_SAVINGS']]

In [27]:
total_savings_data_2013

        CASEID  TOTAL_SAVINGS
177565  177566            0.0
177566  177567            0.0
177567  177568            0.0
177568  177569            0.0
177569  177570            0.0
177570  177571         1000.0
177571  177572         1000.0
177572  177573         1000.0
177573  177574         1000.0
177574  177575         1000.0
177575  177576            0.0
177576  177577            0.0
177577  177578            0.0
177578  177579            0.0
177579  177580            0.0
177580  177581        38200.0
177581  177582        38200.0
177582  177583        38200.0
177583  177584        38200.0
177584  177585        38200.0
177585  177586        30000.0
177586  177587        30000.0
177587  177588        30000.0
177588  177589        30000.0
177589  177590        30000.0
177590  177591            0.0
177591  177592            0.0
177592  177593            0.0
177593  177594            0.0
177594  177595            0.0
...        ...            ...
207610  207611        70000.0
207611  207612        70000.0
207612  207613        70000.0
207613  207614        70000.0
207614  207615        70000.0
207615  207616        27000.0
207616  207617        32000.0
207617  207618        41000.0
207618  207619        32000.0
207619  207620        44000.0
207620  207621            0.0
207621  207622            0.0
207622  207623            0.0
207623  207624            0.0
207624  207625            0.0
207625  207626         1200.0
207626  207627         1200.0
207627  207628         1300.0
207628  207629         1300.0
207629  207630         1100.0
207630  207631            0.0
207631  207632            0.0
207632  207633            0.0
207633  207634            0.0
207634  207635            0.0
207635  207636            0.0
207636  207637            0.0
207637  207638            0.0
207638  207639            0.0
207639  207640            0.0

[30075 rows x 2 columns]

In [28]:
households_with_savings_2013 = total_savings_data_2013[total_savings_data_2013['TOTAL_SAVINGS'] > 0]

In [29]:
households_with_savings_2013

        CASEID  TOTAL_SAVINGS
177570  177571         1000.0
177571  177572         1000.0
177572  177573         1000.0
177573  177574         1000.0
177574  177575         1000.0
177580  177581        38200.0
177581  177582        38200.0
177582  177583        38200.0
177583  177584        38200.0
177584  177585        38200.0
177585  177586        30000.0
177586  177587        30000.0
177587  177588        30000.0
177588  177589        30000.0
177589  177590        30000.0
177595  177596         2600.0
177596  177597         2600.0
177597  177598         2600.0
177598  177599         2600.0
177599  177600         2600.0
177600  177601         1390.0
177601  177602         1400.0
177602  177603         1390.0
177603  177604         1390.0
177604  177605         1400.0
177605  177606          310.0
177606  177607          320.0
177607  177608          310.0
177608  177609          320.0
177609  177610          320.0
...        ...            ...
207590  207591       519000.0
207591  207592       486000.0
207592  207593       454000.0
207593  207594       478000.0
207594  207595       479000.0
207595  207596        10200.0
207596  207597        10130.0
207597  207598        10530.0
207598  207599         8230.0
207599  207600        10500.0
207605  207606        12030.0
207606  207607        12040.0
207607  207608        12030.0
207608  207609        12030.0
207609  207610        12040.0
207610  207611        70000.0
207611  207612        70000.0
207612  207613        70000.0
207613  207614        70000.0
207614  207615        70000.0
207615  207616        27000.0
207616  207617        32000.0
207617  207618        41000.0
207618  207619        32000.0
207619  207620        44000.0
207625  207626         1200.0
207626  207627         1200.0
207627  207628         1300.0
207628  207629         1300.0
207629  207630         1100.0

[17770 rows x 2 columns]

In [30]:
median_total_savings_2013=households_with_savings_2013.TOTAL_SAVINGS.median()

In [31]:
median_total_savings_2013

10000.0

In [32]:
data_2010 = data[data.YEAR == 2010]

In [33]:
data_2010

        CASEID  YEAR    SAVING      MMDA  TOTAL_SAVINGS
145155  145156  2010  27864.09      0.00       27864.09
145156  145157  2010    664.45      0.00         664.45
145157  145158  2010  35365.96      0.00       35365.96
145158  145159  2010   1821.88      0.00        1821.88
145159  145160  2010   1500.37      0.00        1500.37
145160  145161  2010  32150.87   1607.54       33758.41
145161  145162  2010  32150.87   1607.54       33758.41
145162  145163  2010  32150.87   1607.54       33758.41
145163  145164  2010  32150.87   1607.54       33758.41
145164  145165  2010  32150.87   1607.54       33758.41
145165  145166  2010      0.00      0.00           0.00
145166  145167  2010      0.00      0.00           0.00
145167  145168  2010      0.00      0.00           0.00
145168  145169  2010      0.00      0.00           0.00
145169  145170  2010      0.00      0.00           0.00
145170  145171  2010   2572.07      0.00        2572.07
145171  145172  2010   2679.24      0.00        2679.24
145172  145173  2010  10181.11      0.00       10181.11
145173  145174  2010    310.79      0.00         310.79
145174  145175  2010   1393.20      0.00        1393.20
145175  145176  2010    107.17      0.00         107.17
145176  145177  2010    107.17      0.00         107.17
145177  145178  2010    107.17      0.00         107.17
145178  145179  2010    107.17      0.00         107.17
145179  145180  2010    107.17      0.00         107.17
145180  145181  2010    364.38      0.00         364.38
145181  145182  2010    364.38      0.00         364.38
145182  145183  2010    364.38      0.00         364.38
145183  145184  2010    364.38      0.00         364.38
145184  145185  2010    364.38      0.00         364.38
...        ...   ...       ...       ...            ...
177535  177536  2010  22076.93  55728.18       77805.11
177536  177537  2010  22076.93  55728.18       77805.11
177537  177538  2010  22076.93  55728.18       77805.11
177538  177539  2010  22076.93  55728.18       77805.11
177539  177540  2010  22076.93  55728.18       77805.11
177540  177541  2010      0.00  11788.65       11788.65
177541  177542  2010      0.00  23577.31       23577.31
177542  177543  2010      0.00  26792.39       26792.39
177543  177544  2010      0.00  13932.04       13932.04
177544  177545  2010      0.00  24649.00       24649.00
177545  177546  2010      0.00      0.00           0.00
177546  177547  2010      0.00      0.00           0.00
177547  177548  2010      0.00      0.00           0.00
177548  177549  2010      0.00      0.00           0.00
177549  177550  2010      0.00      0.00           0.00
177550  177551  2010      0.00      0.00           0.00
177551  177552  2010      0.00      0.00           0.00
177552  177553  2010      0.00      0.00           0.00
177553  177554  2010      0.00      0.00           0.00
177554  177555  2010      0.00      0.00           0.00
177555  177556  2010     53.58      0.00          53.58
177556  177557  2010     53.58      0.00          53.58
177557  177558  2010     53.58      0.00          53.58
177558  177559  2010     53.58      0.00          53.58
177559  177560  2010     53.58      0.00          53.58
177560  177561  2010      0.00      0.00           0.00
177561  177562  2010      0.00      0.00           0.00
177562  177563  2010      0.00      0.00           0.00
177563  177564  2010      0.00      0.00           0.00
177564  177565  2010      0.00      0.00           0.00

[32410 rows x 5 columns]

In [34]:
data_2010.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32410 entries, 145155 to 177564
Data columns (total 5 columns):
CASEID           32410 non-null int64
YEAR             32410 non-null int64
SAVING           32410 non-null float64
MMDA             32410 non-null float64
TOTAL_SAVINGS    32410 non-null float64
dtypes: float64(3), int64(2)
memory usage: 1.5 MB

In [35]:
total_savings_data_2010=data_2010[['CASEID','TOTAL_SAVINGS']]

In [36]:
total_savings_data_2010

        CASEID  TOTAL_SAVINGS
145155  145156       27864.09
145156  145157         664.45
145157  145158       35365.96
145158  145159        1821.88
145159  145160        1500.37
145160  145161       33758.41
145161  145162       33758.41
145162  145163       33758.41
145163  145164       33758.41
145164  145165       33758.41
145165  145166           0.00
145166  145167           0.00
145167  145168           0.00
145168  145169           0.00
145169  145170           0.00
145170  145171        2572.07
145171  145172        2679.24
145172  145173       10181.11
145173  145174         310.79
145174  145175        1393.20
145175  145176         107.17
145176  145177         107.17
145177  145178         107.17
145178  145179         107.17
145179  145180         107.17
145180  145181         364.38
145181  145182         364.38
145182  145183         364.38
145183  145184         364.38
145184  145185         364.38
...        ...            ...
177535  177536       77805.11
177536  177537       77805.11
177537  177538       77805.11
177538  177539       77805.11
177539  177540       77805.11
177540  177541       11788.65
177541  177542       23577.31
177542  177543       26792.39
177543  177544       13932.04
177544  177545       24649.00
177545  177546           0.00
177546  177547           0.00
177547  177548           0.00
177548  177549           0.00
177549  177550           0.00
177550  177551           0.00
177551  177552           0.00
177552  177553           0.00
177553  177554           0.00
177554  177555           0.00
177555  177556          53.58
177556  177557          53.58
177557  177558          53.58
177558  177559          53.58
177559  177560          53.58
177560  177561           0.00
177561  177562           0.00
177562  177563           0.00
177563  177564           0.00
177564  177565           0.00

[32410 rows x 2 columns]

In [37]:
households_with_savings_2010 = total_savings_data_2010[total_savings_data_2010['TOTAL_SAVINGS'] > 0]

In [38]:
households_with_savings_2010

        CASEID  TOTAL_SAVINGS
145155  145156       27864.09
145156  145157         664.45
145157  145158       35365.96
145158  145159        1821.88
145159  145160        1500.37
145160  145161       33758.41
145161  145162       33758.41
145162  145163       33758.41
145163  145164       33758.41
145164  145165       33758.41
145170  145171        2572.07
145171  145172        2679.24
145172  145173       10181.11
145173  145174         310.79
145174  145175        1393.20
145175  145176         107.17
145176  145177         107.17
145177  145178         107.17
145178  145179         107.17
145179  145180         107.17
145180  145181         364.38
145181  145182         364.38
145182  145183         364.38
145183  145184         364.38
145184  145185         364.38
145185  145186         600.15
145186  145187         975.24
145187  145188         643.02
145188  145189         621.58
145189  145190         932.38
...        ...            ...
177510  177511        8573.57
177511  177512        8573.57
177512  177513        8573.57
177513  177514        8573.57
177514  177515        8573.57
177515  177516      152716.65
177516  177517      152716.65
177517  177518      152716.65
177518  177519      152716.65
177519  177520      152716.65
177530  177531           1.07
177531  177532           1.07
177532  177533           1.07
177533  177534           1.07
177534  177535           1.07
177535  177536       77805.11
177536  177537       77805.11
177537  177538       77805.11
177538  177539       77805.11
177539  177540       77805.11
177540  177541       11788.65
177541  177542       23577.31
177542  177543       26792.39
177543  177544       13932.04
177544  177545       24649.00
177555  177556          53.58
177556  177557          53.58
177557  177558          53.58
177558  177559          53.58
177559  177560          53.58

[19600 rows x 2 columns]

In [43]:
median_total_savings_2010=households_with_savings_2010.TOTAL_SAVINGS.median()

In [44]:
median_total_savings_2010

7501.87

In [ ]:
data_2007 = data[data.YEAR == 2007]

In [ ]:
data_2007

In [ ]:
data_2007.info()

In [ ]:
savings_data_2007=data_2007[['CASEID','TOTAL_SAVINGS']]

In [ ]:
savings_data_2007

In [ ]:
households_with_savings_2007 = savings_data_2007[savings_data_2007['TOTAL_SAVINGS'] > 0]

In [ ]:
households_with_savings_2007

In [ ]:
median_savings_2007=households_with_savings_2007.SAVING.median()

In [ ]:
median_savings_2007

In [ ]:
data_2004 = data[data.YEAR == 2004]

In [ ]:
data_2004

In [ ]:
data_2004.info()

In [ ]:
savings_data_2004=data_2004[['CASEID','TOTAL_SAVINGS']]

In [ ]:
savings_data_2004

In [ ]:
households_with_savings_2004 = savings_data_2004[savings_data_2004['TOTAL_SAVINGS'] > 0]

In [ ]:
households_with_savings_2004

In [ ]:
median_savings_2004=households_with_savings_2004.SAVING.median()

In [ ]:
median_savings_2004