In [144]:
import pandas as pd

In [145]:
data = pd.read_csv('survey-consumer-finances-data.csv')

In [146]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207640 entries, 0 to 207639
Data columns (total 4 columns):
CASEID    207640 non-null int64
YEAR      207640 non-null int64
SAVING    207640 non-null float64
MMDA      207640 non-null float64
dtypes: float64(2), int64(2)
memory usage: 6.3 MB

In [147]:
data['TOTAL_SAVINGS'] = data['SAVING'] + data['MMDA']

In [148]:
data_2013 = data[data.YEAR == 2013]

In [149]:
data_2013

        CASEID  YEAR   SAVING     MMDA  TOTAL_SAVINGS
177565  177566  2013      0.0      0.0            0.0
177566  177567  2013      0.0      0.0            0.0
177567  177568  2013      0.0      0.0            0.0
177568  177569  2013      0.0      0.0            0.0
177569  177570  2013      0.0      0.0            0.0
177570  177571  2013   1000.0      0.0         1000.0
177571  177572  2013   1000.0      0.0         1000.0
177572  177573  2013   1000.0      0.0         1000.0
177573  177574  2013   1000.0      0.0         1000.0
177574  177575  2013   1000.0      0.0         1000.0
177575  177576  2013      0.0      0.0            0.0
177576  177577  2013      0.0      0.0            0.0
177577  177578  2013      0.0      0.0            0.0
177578  177579  2013      0.0      0.0            0.0
177579  177580  2013      0.0      0.0            0.0
177580  177581  2013   1200.0  37000.0        38200.0
177581  177582  2013   1200.0  37000.0        38200.0
177582  177583  2013   1200.0  37000.0        38200.0
177583  177584  2013   1200.0  37000.0        38200.0
177584  177585  2013   1200.0  37000.0        38200.0
177585  177586  2013      0.0  30000.0        30000.0
177586  177587  2013      0.0  30000.0        30000.0
177587  177588  2013      0.0  30000.0        30000.0
177588  177589  2013      0.0  30000.0        30000.0
177589  177590  2013      0.0  30000.0        30000.0
177590  177591  2013      0.0      0.0            0.0
177591  177592  2013      0.0      0.0            0.0
177592  177593  2013      0.0      0.0            0.0
177593  177594  2013      0.0      0.0            0.0
177594  177595  2013      0.0      0.0            0.0
...        ...   ...      ...      ...            ...
207610  207611  2013  70000.0      0.0        70000.0
207611  207612  2013  70000.0      0.0        70000.0
207612  207613  2013  70000.0      0.0        70000.0
207613  207614  2013  70000.0      0.0        70000.0
207614  207615  2013  70000.0      0.0        70000.0
207615  207616  2013      0.0  27000.0        27000.0
207616  207617  2013      0.0  32000.0        32000.0
207617  207618  2013      0.0  41000.0        41000.0
207618  207619  2013      0.0  32000.0        32000.0
207619  207620  2013      0.0  44000.0        44000.0
207620  207621  2013      0.0      0.0            0.0
207621  207622  2013      0.0      0.0            0.0
207622  207623  2013      0.0      0.0            0.0
207623  207624  2013      0.0      0.0            0.0
207624  207625  2013      0.0      0.0            0.0
207625  207626  2013   1200.0      0.0         1200.0
207626  207627  2013   1200.0      0.0         1200.0
207627  207628  2013   1300.0      0.0         1300.0
207628  207629  2013   1300.0      0.0         1300.0
207629  207630  2013   1100.0      0.0         1100.0
207630  207631  2013      0.0      0.0            0.0
207631  207632  2013      0.0      0.0            0.0
207632  207633  2013      0.0      0.0            0.0
207633  207634  2013      0.0      0.0            0.0
207634  207635  2013      0.0      0.0            0.0
207635  207636  2013      0.0      0.0            0.0
207636  207637  2013      0.0      0.0            0.0
207637  207638  2013      0.0      0.0            0.0
207638  207639  2013      0.0      0.0            0.0
207639  207640  2013      0.0      0.0            0.0

[30075 rows x 5 columns]

In [150]:
data_2013.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30075 entries, 177565 to 207639
Data columns (total 5 columns):
CASEID           30075 non-null int64
YEAR             30075 non-null int64
SAVING           30075 non-null float64
MMDA             30075 non-null float64
TOTAL_SAVINGS    30075 non-null float64
dtypes: float64(3), int64(2)
memory usage: 1.4 MB

In [186]:
savings_data_2013=data_2013[['CASEID','SAVING']]

In [187]:
savings_data_2013

        CASEID   SAVING
177565  177566      0.0
177566  177567      0.0
177567  177568      0.0
177568  177569      0.0
177569  177570      0.0
177570  177571   1000.0
177571  177572   1000.0
177572  177573   1000.0
177573  177574   1000.0
177574  177575   1000.0
177575  177576      0.0
177576  177577      0.0
177577  177578      0.0
177578  177579      0.0
177579  177580      0.0
177580  177581   1200.0
177581  177582   1200.0
177582  177583   1200.0
177583  177584   1200.0
177584  177585   1200.0
177585  177586      0.0
177586  177587      0.0
177587  177588      0.0
177588  177589      0.0
177589  177590      0.0
177590  177591      0.0
177591  177592      0.0
177592  177593      0.0
177593  177594      0.0
177594  177595      0.0
...        ...      ...
207610  207611  70000.0
207611  207612  70000.0
207612  207613  70000.0
207613  207614  70000.0
207614  207615  70000.0
207615  207616      0.0
207616  207617      0.0
207617  207618      0.0
207618  207619      0.0
207619  207620      0.0
207620  207621      0.0
207621  207622      0.0
207622  207623      0.0
207623  207624      0.0
207624  207625      0.0
207625  207626   1200.0
207626  207627   1200.0
207627  207628   1300.0
207628  207629   1300.0
207629  207630   1100.0
207630  207631      0.0
207631  207632      0.0
207632  207633      0.0
207633  207634      0.0
207634  207635      0.0
207635  207636      0.0
207636  207637      0.0
207637  207638      0.0
207638  207639      0.0
207639  207640      0.0

[30075 rows x 2 columns]

In [153]:
households_with_savings_2013 = savings_data_2013[savings_data_2013['SAVING'] > 0]

In [154]:
households_with_savings_2013

        CASEID   SAVING  TOTAL_SAVINGS
177570  177571   1000.0         1000.0
177571  177572   1000.0         1000.0
177572  177573   1000.0         1000.0
177573  177574   1000.0         1000.0
177574  177575   1000.0         1000.0
177580  177581   1200.0        38200.0
177581  177582   1200.0        38200.0
177582  177583   1200.0        38200.0
177583  177584   1200.0        38200.0
177584  177585   1200.0        38200.0
177595  177596   1400.0         2600.0
177596  177597   1400.0         2600.0
177597  177598   1400.0         2600.0
177598  177599   1400.0         2600.0
177599  177600   1400.0         2600.0
177600  177601   1390.0         1390.0
177601  177602   1400.0         1400.0
177602  177603   1390.0         1390.0
177603  177604   1390.0         1390.0
177604  177605   1400.0         1400.0
177605  177606    310.0          310.0
177606  177607    320.0          320.0
177607  177608    310.0          310.0
177608  177609    320.0          320.0
177609  177610    320.0          320.0
177620  177621   8290.0         8290.0
177621  177622   8180.0         8180.0
177622  177623   8100.0         8100.0
177623  177624   8240.0         8240.0
177624  177625   8200.0         8200.0
...        ...      ...            ...
207580  207581   8000.0         8000.0
207581  207582   8000.0         8000.0
207582  207583   8000.0         8000.0
207583  207584   8000.0         8000.0
207584  207585   8000.0         8000.0
207585  207586   3000.0         3000.0
207586  207587   2900.0         2900.0
207587  207588   3200.0         3200.0
207588  207589   2900.0         2900.0
207589  207590   3100.0         3100.0
207595  207596  10200.0        10200.0
207596  207597  10130.0        10130.0
207597  207598  10530.0        10530.0
207598  207599   8230.0         8230.0
207599  207600  10500.0        10500.0
207605  207606  12030.0        12030.0
207606  207607  12040.0        12040.0
207607  207608  12030.0        12030.0
207608  207609  12030.0        12030.0
207609  207610  12040.0        12040.0
207610  207611  70000.0        70000.0
207611  207612  70000.0        70000.0
207612  207613  70000.0        70000.0
207613  207614  70000.0        70000.0
207614  207615  70000.0        70000.0
207625  207626   1200.0         1200.0
207626  207627   1200.0         1200.0
207627  207628   1300.0         1300.0
207628  207629   1300.0         1300.0
207629  207630   1100.0         1100.0

[14724 rows x 3 columns]

In [155]:
median_savings_2013=households_with_savings_2013.SAVING.median()

In [156]:
median_savings_2013

5200.0

In [157]:
data_2010 = data[data.YEAR == 2010]

In [158]:
data_2010

        CASEID  YEAR    SAVING      MMDA  TOTAL_SAVINGS
145155  145156  2010  27864.09      0.00       27864.09
145156  145157  2010    664.45      0.00         664.45
145157  145158  2010  35365.96      0.00       35365.96
145158  145159  2010   1821.88      0.00        1821.88
145159  145160  2010   1500.37      0.00        1500.37
145160  145161  2010  32150.87   1607.54       33758.41
145161  145162  2010  32150.87   1607.54       33758.41
145162  145163  2010  32150.87   1607.54       33758.41
145163  145164  2010  32150.87   1607.54       33758.41
145164  145165  2010  32150.87   1607.54       33758.41
145165  145166  2010      0.00      0.00           0.00
145166  145167  2010      0.00      0.00           0.00
145167  145168  2010      0.00      0.00           0.00
145168  145169  2010      0.00      0.00           0.00
145169  145170  2010      0.00      0.00           0.00
145170  145171  2010   2572.07      0.00        2572.07
145171  145172  2010   2679.24      0.00        2679.24
145172  145173  2010  10181.11      0.00       10181.11
145173  145174  2010    310.79      0.00         310.79
145174  145175  2010   1393.20      0.00        1393.20
145175  145176  2010    107.17      0.00         107.17
145176  145177  2010    107.17      0.00         107.17
145177  145178  2010    107.17      0.00         107.17
145178  145179  2010    107.17      0.00         107.17
145179  145180  2010    107.17      0.00         107.17
145180  145181  2010    364.38      0.00         364.38
145181  145182  2010    364.38      0.00         364.38
145182  145183  2010    364.38      0.00         364.38
145183  145184  2010    364.38      0.00         364.38
145184  145185  2010    364.38      0.00         364.38
...        ...   ...       ...       ...            ...
177535  177536  2010  22076.93  55728.18       77805.11
177536  177537  2010  22076.93  55728.18       77805.11
177537  177538  2010  22076.93  55728.18       77805.11
177538  177539  2010  22076.93  55728.18       77805.11
177539  177540  2010  22076.93  55728.18       77805.11
177540  177541  2010      0.00  11788.65       11788.65
177541  177542  2010      0.00  23577.31       23577.31
177542  177543  2010      0.00  26792.39       26792.39
177543  177544  2010      0.00  13932.04       13932.04
177544  177545  2010      0.00  24649.00       24649.00
177545  177546  2010      0.00      0.00           0.00
177546  177547  2010      0.00      0.00           0.00
177547  177548  2010      0.00      0.00           0.00
177548  177549  2010      0.00      0.00           0.00
177549  177550  2010      0.00      0.00           0.00
177550  177551  2010      0.00      0.00           0.00
177551  177552  2010      0.00      0.00           0.00
177552  177553  2010      0.00      0.00           0.00
177553  177554  2010      0.00      0.00           0.00
177554  177555  2010      0.00      0.00           0.00
177555  177556  2010     53.58      0.00          53.58
177556  177557  2010     53.58      0.00          53.58
177557  177558  2010     53.58      0.00          53.58
177558  177559  2010     53.58      0.00          53.58
177559  177560  2010     53.58      0.00          53.58
177560  177561  2010      0.00      0.00           0.00
177561  177562  2010      0.00      0.00           0.00
177562  177563  2010      0.00      0.00           0.00
177563  177564  2010      0.00      0.00           0.00
177564  177565  2010      0.00      0.00           0.00

[32410 rows x 5 columns]

In [159]:
data_2010.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32410 entries, 145155 to 177564
Data columns (total 5 columns):
CASEID           32410 non-null int64
YEAR             32410 non-null int64
SAVING           32410 non-null float64
MMDA             32410 non-null float64
TOTAL_SAVINGS    32410 non-null float64
dtypes: float64(3), int64(2)
memory usage: 1.5 MB

In [184]:
savings_data_2010=data_2010[['CASEID','SAVING']]

In [185]:
savings_data_2010

        CASEID    SAVING
145155  145156  27864.09
145156  145157    664.45
145157  145158  35365.96
145158  145159   1821.88
145159  145160   1500.37
145160  145161  32150.87
145161  145162  32150.87
145162  145163  32150.87
145163  145164  32150.87
145164  145165  32150.87
145165  145166      0.00
145166  145167      0.00
145167  145168      0.00
145168  145169      0.00
145169  145170      0.00
145170  145171   2572.07
145171  145172   2679.24
145172  145173  10181.11
145173  145174    310.79
145174  145175   1393.20
145175  145176    107.17
145176  145177    107.17
145177  145178    107.17
145178  145179    107.17
145179  145180    107.17
145180  145181    364.38
145181  145182    364.38
145182  145183    364.38
145183  145184    364.38
145184  145185    364.38
...        ...       ...
177535  177536  22076.93
177536  177537  22076.93
177537  177538  22076.93
177538  177539  22076.93
177539  177540  22076.93
177540  177541      0.00
177541  177542      0.00
177542  177543      0.00
177543  177544      0.00
177544  177545      0.00
177545  177546      0.00
177546  177547      0.00
177547  177548      0.00
177548  177549      0.00
177549  177550      0.00
177550  177551      0.00
177551  177552      0.00
177552  177553      0.00
177553  177554      0.00
177554  177555      0.00
177555  177556     53.58
177556  177557     53.58
177557  177558     53.58
177558  177559     53.58
177559  177560     53.58
177560  177561      0.00
177561  177562      0.00
177562  177563      0.00
177563  177564      0.00
177564  177565      0.00

[32410 rows x 2 columns]

In [162]:
households_with_savings_2010 = savings_data_2010[savings_data_2010['SAVING'] > 0]

In [163]:
households_with_savings_2010

        CASEID     SAVING  TOTAL_SAVINGS
145155  145156   27864.09       27864.09
145156  145157     664.45         664.45
145157  145158   35365.96       35365.96
145158  145159    1821.88        1821.88
145159  145160    1500.37        1500.37
145160  145161   32150.87       33758.41
145161  145162   32150.87       33758.41
145162  145163   32150.87       33758.41
145163  145164   32150.87       33758.41
145164  145165   32150.87       33758.41
145170  145171    2572.07        2572.07
145171  145172    2679.24        2679.24
145172  145173   10181.11       10181.11
145173  145174     310.79         310.79
145174  145175    1393.20        1393.20
145175  145176     107.17         107.17
145176  145177     107.17         107.17
145177  145178     107.17         107.17
145178  145179     107.17         107.17
145179  145180     107.17         107.17
145180  145181     364.38         364.38
145181  145182     364.38         364.38
145182  145183     364.38         364.38
145183  145184     364.38         364.38
145184  145185     364.38         364.38
145185  145186     600.15         600.15
145186  145187     975.24         975.24
145187  145188     643.02         643.02
145188  145189     621.58         621.58
145189  145190     932.38         932.38
...        ...        ...            ...
177490  177491  105240.52      107791.16
177491  177492  105240.52      107791.16
177492  177493  105240.52      107791.16
177493  177494  105240.52      107791.16
177494  177495  105240.52      107791.16
177495  177496   78233.79       98596.01
177496  177497   99667.71      115743.15
177497  177498   41796.13       62158.35
177498  177499  102882.79      114671.44
177499  177500   39652.74       51441.39
177510  177511    8573.57        8573.57
177511  177512    8573.57        8573.57
177512  177513    8573.57        8573.57
177513  177514    8573.57        8573.57
177514  177515    8573.57        8573.57
177515  177516    1071.70      152716.65
177516  177517    1071.70      152716.65
177517  177518    1071.70      152716.65
177518  177519    1071.70      152716.65
177519  177520    1071.70      152716.65
177535  177536   22076.93       77805.11
177536  177537   22076.93       77805.11
177537  177538   22076.93       77805.11
177538  177539   22076.93       77805.11
177539  177540   22076.93       77805.11
177555  177556      53.58          53.58
177556  177557      53.58          53.58
177557  177558      53.58          53.58
177558  177559      53.58          53.58
177559  177560      53.58          53.58

[15836 rows x 3 columns]

In [164]:
median_savings_2010=households_with_savings_2010.SAVING.median()

In [165]:
median_savings_2010

3911.69

In [166]:
data_2007 = data[data.YEAR == 2007]

In [167]:
data_2007

        CASEID  YEAR     SAVING       MMDA  TOTAL_SAVINGS
123070  123071  2007       0.00     516.49         516.49
123071  123072  2007       0.00     516.49         516.49
123072  123073  2007       0.00     516.49         516.49
123073  123074  2007       0.00     527.71         527.71
123074  123075  2007       0.00     516.49         516.49
123075  123076  2007       0.00       0.00           0.00
123076  123077  2007       0.00       0.00           0.00
123077  123078  2007       0.00       0.00           0.00
123078  123079  2007       0.00       0.00           0.00
123079  123080  2007       0.00       0.00           0.00
123080  123081  2007    2806.99       0.00        2806.99
123081  123082  2007    2806.99       0.00        2806.99
123082  123083  2007    2806.99       0.00        2806.99
123083  123084  2007    2806.99       0.00        2806.99
123084  123085  2007    2806.99       0.00        2806.99
123085  123086  2007    7859.57   39297.84       47157.41
123086  123087  2007    7859.57   39297.84       47157.41
123087  123088  2007    7859.57   39297.84       47157.41
123088  123089  2007    7859.57   39297.84       47157.41
123089  123090  2007    7859.57   39297.84       47157.41
123090  123091  2007    1122.80       0.00        1122.80
123091  123092  2007    1122.80       0.00        1122.80
123092  123093  2007    1122.80       0.00        1122.80
123093  123094  2007    1122.80       0.00        1122.80
123094  123095  2007    1122.80       0.00        1122.80
123095  123096  2007       0.00   19648.92       19648.92
123096  123097  2007       0.00   19648.92       19648.92
123097  123098  2007       0.00   19648.92       19648.92
123098  123099  2007       0.00   19648.92       19648.92
123099  123100  2007       0.00   19648.92       19648.92
...        ...   ...        ...        ...            ...
145125  145126  2007       0.00   35929.46       35929.46
145126  145127  2007       0.00   35929.46       35929.46
145127  145128  2007       0.00   35929.46       35929.46
145128  145129  2007       0.00   35929.46       35929.46
145129  145130  2007       0.00   35929.46       35929.46
145130  145131  2007       0.00  231295.89      231295.89
145131  145132  2007       0.00  247688.70      247688.70
145132  145133  2007       0.00  247015.02      247015.02
145133  145134  2007       0.00  207717.18      207717.18
145134  145135  2007       0.00  238818.62      238818.62
145135  145136  2007       0.00   30315.48       30315.48
145136  145137  2007       0.00   11227.96       11227.96
145137  145138  2007       0.00   29192.68       29192.68
145138  145139  2007       0.00    8420.97        8420.97
145139  145140  2007       0.00   35929.46       35929.46
145140  145141  2007       0.00       0.00           0.00
145141  145142  2007       0.00       0.00           0.00
145142  145143  2007       0.00       0.00           0.00
145143  145144  2007       0.00       0.00           0.00
145144  145145  2007       0.00       0.00           0.00
145145  145146  2007   17291.05       0.00       17291.05
145146  145147  2007   10677.79       0.00       10677.79
145147  145148  2007  100714.76       0.00      100714.76
145148  145149  2007  105542.78       0.00      105542.78
145149  145150  2007   48931.43       0.00       48931.43
145150  145151  2007   22736.61       0.00       22736.61
145151  145152  2007   22736.61       0.00       22736.61
145152  145153  2007   22736.61       0.00       22736.61
145153  145154  2007   22736.61       0.00       22736.61
145154  145155  2007   22736.61       0.00       22736.61

[22085 rows x 5 columns]

In [168]:
data_2007.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22085 entries, 123070 to 145154
Data columns (total 5 columns):
CASEID           22085 non-null int64
YEAR             22085 non-null int64
SAVING           22085 non-null float64
MMDA             22085 non-null float64
TOTAL_SAVINGS    22085 non-null float64
dtypes: float64(3), int64(2)
memory usage: 1.0 MB

In [169]:
savings_data_2007=data_2007[['CASEID','SAVING']]

In [170]:
savings_data_2007

        CASEID     SAVING
123070  123071       0.00
123071  123072       0.00
123072  123073       0.00
123073  123074       0.00
123074  123075       0.00
123075  123076       0.00
123076  123077       0.00
123077  123078       0.00
123078  123079       0.00
123079  123080       0.00
123080  123081    2806.99
123081  123082    2806.99
123082  123083    2806.99
123083  123084    2806.99
123084  123085    2806.99
123085  123086    7859.57
123086  123087    7859.57
123087  123088    7859.57
123088  123089    7859.57
123089  123090    7859.57
123090  123091    1122.80
123091  123092    1122.80
123092  123093    1122.80
123093  123094    1122.80
123094  123095    1122.80
123095  123096       0.00
123096  123097       0.00
123097  123098       0.00
123098  123099       0.00
123099  123100       0.00
...        ...        ...
145125  145126       0.00
145126  145127       0.00
145127  145128       0.00
145128  145129       0.00
145129  145130       0.00
145130  145131       0.00
145131  145132       0.00
145132  145133       0.00
145133  145134       0.00
145134  145135       0.00
145135  145136       0.00
145136  145137       0.00
145137  145138       0.00
145138  145139       0.00
145139  145140       0.00
145140  145141       0.00
145141  145142       0.00
145142  145143       0.00
145143  145144       0.00
145144  145145       0.00
145145  145146   17291.05
145146  145147   10677.79
145147  145148  100714.76
145148  145149  105542.78
145149  145150   48931.43
145150  145151   22736.61
145151  145152   22736.61
145152  145153   22736.61
145153  145154   22736.61
145154  145155   22736.61

[22085 rows x 2 columns]

In [171]:
households_with_savings_2007 = savings_data_2007[savings_data_2007['SAVING'] > 0]

In [172]:
households_with_savings_2007

        CASEID     SAVING
123080  123081    2806.99
123081  123082    2806.99
123082  123083    2806.99
123083  123084    2806.99
123084  123085    2806.99
123085  123086    7859.57
123086  123087    7859.57
123087  123088    7859.57
123088  123089    7859.57
123089  123090    7859.57
123090  123091    1122.80
123091  123092    1122.80
123092  123093    1122.80
123093  123094    1122.80
123094  123095    1122.80
123105  123106     561.40
123106  123107     561.40
123107  123108     561.40
123108  123109     561.40
123109  123110     561.40
123125  123126      11.23
123126  123127      11.23
123127  123128      11.23
123128  123129      11.23
123129  123130      11.23
123130  123131    8982.36
123131  123132    9880.60
123132  123133    8982.36
123133  123134   10105.16
123134  123135    8982.36
...        ...        ...
145045  145046   16280.54
145046  145047   16280.54
145047  145048   16280.54
145048  145049   16280.54
145049  145050   16280.54
145070  145071    1684.19
145071  145072    1684.19
145072  145073    1684.19
145073  145074    1684.19
145074  145075    1684.19
145100  145101    8982.36
145101  145102    8982.36
145102  145103    8982.36
145103  145104    8982.36
145104  145105    8982.36
145120  145121    2245.59
145121  145122    2245.59
145122  145123    2245.59
145123  145124    2245.59
145124  145125    2245.59
145145  145146   17291.05
145146  145147   10677.79
145147  145148  100714.76
145148  145149  105542.78
145149  145150   48931.43
145150  145151   22736.61
145151  145152   22736.61
145152  145153   22736.61
145153  145154   22736.61
145154  145155   22736.61

[9693 rows x 2 columns]

In [173]:
median_savings_2007=households_with_savings_2007.SAVING.median()

In [174]:
median_savings_2007

5557.84

In [175]:
data_2004 = data[data.YEAR == 2004]

In [176]:
data_2004

        CASEID  YEAR     SAVING      MMDA  TOTAL_SAVINGS
100475  100476  2004       0.00      0.00           0.00
100476  100477  2004       0.00      0.00           0.00
100477  100478  2004       0.00      0.00           0.00
100478  100479  2004       0.00      0.00           0.00
100479  100480  2004       0.00      0.00           0.00
100480  100481  2004       0.00  25895.98       25895.98
100481  100482  2004       0.00  25895.98       25895.98
100482  100483  2004       0.00  25895.98       25895.98
100483  100484  2004       0.00  25895.98       25895.98
100484  100485  2004       0.00  25895.98       25895.98
100485  100486  2004  197302.73  20914.09      218216.82
100486  100487  2004  197302.73  20470.16      217772.89
100487  100488  2004  197302.73  20470.16      217772.89
100488  100489  2004  147977.04  70264.43      218241.47
100489  100490  2004  197302.73  20938.75      218241.48
100490  100491  2004       0.00      0.00           0.00
100491  100492  2004       0.00      0.00           0.00
100492  100493  2004       0.00      0.00           0.00
100493  100494  2004       0.00      0.00           0.00
100494  100495  2004       0.00      0.00           0.00
100495  100496  2004       0.00      0.00           0.00
100496  100497  2004       0.00      0.00           0.00
100497  100498  2004       0.00      0.00           0.00
100498  100499  2004       0.00      0.00           0.00
100499  100500  2004       0.00      0.00           0.00
100500  100501  2004       0.00      0.00           0.00
100501  100502  2004       0.00      0.00           0.00
100502  100503  2004       0.00      0.00           0.00
100503  100504  2004       0.00      0.00           0.00
100504  100505  2004       0.00      0.00           0.00
...        ...   ...        ...       ...            ...
123040  123041  2004       0.00      0.00           0.00
123041  123042  2004       0.00      0.00           0.00
123042  123043  2004       0.00      0.00           0.00
123043  123044  2004       0.00      0.00           0.00
123044  123045  2004       0.00      0.00           0.00
123045  123046  2004   11714.85      0.00       11714.85
123046  123047  2004   10235.08      0.00       10235.08
123047  123048  2004   11961.48      0.00       11961.48
123048  123049  2004   10728.34      0.00       10728.34
123049  123050  2004   11098.28      0.00       11098.28
123050  123051  2004       0.00      0.00           0.00
123051  123052  2004       0.00      0.00           0.00
123052  123053  2004       0.00      0.00           0.00
123053  123054  2004       0.00      0.00           0.00
123054  123055  2004       0.00      0.00           0.00
123055  123056  2004       0.00      0.00           0.00
123056  123057  2004       0.00      0.00           0.00
123057  123058  2004       0.00      0.00           0.00
123058  123059  2004       0.00      0.00           0.00
123059  123060  2004       0.00      0.00           0.00
123060  123061  2004    4809.25      0.00        4809.25
123061  123062  2004    4809.25      0.00        4809.25
123062  123063  2004    4809.25      0.00        4809.25
123063  123064  2004    4809.25      0.00        4809.25
123064  123065  2004    4809.25      0.00        4809.25
123065  123066  2004       0.00      0.00           0.00
123066  123067  2004       0.00      0.00           0.00
123067  123068  2004       0.00      0.00           0.00
123068  123069  2004       0.00      0.00           0.00
123069  123070  2004       0.00      0.00           0.00

[22595 rows x 5 columns]

In [177]:
data_2004.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22595 entries, 100475 to 123069
Data columns (total 5 columns):
CASEID           22595 non-null int64
YEAR             22595 non-null int64
SAVING           22595 non-null float64
MMDA             22595 non-null float64
TOTAL_SAVINGS    22595 non-null float64
dtypes: float64(3), int64(2)
memory usage: 1.0 MB

In [178]:
savings_data_2004=data_2004[['CASEID','SAVING']]

In [179]:
savings_data_2004

        CASEID     SAVING
100475  100476       0.00
100476  100477       0.00
100477  100478       0.00
100478  100479       0.00
100479  100480       0.00
100480  100481       0.00
100481  100482       0.00
100482  100483       0.00
100483  100484       0.00
100484  100485       0.00
100485  100486  197302.73
100486  100487  197302.73
100487  100488  197302.73
100488  100489  147977.04
100489  100490  197302.73
100490  100491       0.00
100491  100492       0.00
100492  100493       0.00
100493  100494       0.00
100494  100495       0.00
100495  100496       0.00
100496  100497       0.00
100497  100498       0.00
100498  100499       0.00
100499  100500       0.00
100500  100501       0.00
100501  100502       0.00
100502  100503       0.00
100503  100504       0.00
100504  100505       0.00
...        ...        ...
123040  123041       0.00
123041  123042       0.00
123042  123043       0.00
123043  123044       0.00
123044  123045       0.00
123045  123046   11714.85
123046  123047   10235.08
123047  123048   11961.48
123048  123049   10728.34
123049  123050   11098.28
123050  123051       0.00
123051  123052       0.00
123052  123053       0.00
123053  123054       0.00
123054  123055       0.00
123055  123056       0.00
123056  123057       0.00
123057  123058       0.00
123058  123059       0.00
123059  123060       0.00
123060  123061    4809.25
123061  123062    4809.25
123062  123063    4809.25
123063  123064    4809.25
123064  123065    4809.25
123065  123066       0.00
123066  123067       0.00
123067  123068       0.00
123068  123069       0.00
123069  123070       0.00

[22595 rows x 2 columns]

In [180]:
households_with_savings_2004 = savings_data_2004[savings_data_2004['SAVING'] > 0]

In [181]:
households_with_savings_2004

        CASEID     SAVING
100485  100486  197302.73
100486  100487  197302.73
100487  100488  197302.73
100488  100489  147977.04
100489  100490  197302.73
100505  100506    3699.43
100506  100507    3699.43
100507  100508    3699.43
100508  100509    3699.43
100509  100510    3699.43
100520  100521    5425.82
100521  100522    5425.82
100522  100523    5425.82
100523  100524    5425.82
100524  100525    5425.82
100525  100526    4932.57
100526  100527    4932.57
100527  100528    4932.57
100528  100529    4932.57
100529  100530    4932.57
100530  100531     863.20
100531  100532     863.20
100532  100533     863.20
100533  100534     863.20
100534  100535     863.20
100550  100551   29965.35
100551  100552   29965.35
100552  100553   29965.35
100553  100554   29965.35
100554  100555   29965.35
...        ...        ...
123010  123011    1233.14
123011  123012    1023.51
123012  123013    1233.14
123013  123014    1233.14
123014  123015    1233.14
123015  123016    6165.71
123016  123017    6165.71
123017  123018    6165.71
123018  123019    6165.71
123019  123020    6165.71
123020  123021    3699.43
123021  123022    3699.43
123022  123023    3699.43
123023  123024    3699.43
123024  123025    3699.43
123025  123026    5277.85
123026  123027    4303.67
123027  123028    5080.55
123028  123029    5166.87
123029  123030    5092.88
123045  123046   11714.85
123046  123047   10235.08
123047  123048   11961.48
123048  123049   10728.34
123049  123050   11098.28
123060  123061    4809.25
123061  123062    4809.25
123062  123063    4809.25
123063  123064    4809.25
123064  123065    4809.25

[9910 rows x 2 columns]

In [182]:
median_savings_2004=households_with_savings_2004.SAVING.median()

In [183]:
median_savings_2004

5549.14